-- AlterTable
ALTER TABLE `club` MODIFY `club_order` VARCHAR(191) NULL,
    MODIFY `name` VARCHAR(191) NULL,
    MODIFY `alias` VARCHAR(191) NULL,
    MODIFY `max_class_pilates` INTEGER NULL,
    MODIFY `club_opening_date` DATETIME(3) NULL,
    MODIFY `country_id` VARCHAR(191) NULL,
    MODIFY `city_id` INTEGER NULL,
    MODIFY `state_id` INTEGER NULL,
    MODIFY `address` VARCHAR(191) NULL,
    MODIFY `latitude` VARCHAR(191) NULL,
    MODIFY `longtitude` VARCHAR(191) NULL,
    MODIFY `postal_code` VARCHAR(191) NULL,
    MODIFY `status` INTEGER NULL,
    MODIFY `created_at` DATETIME(3) NULL,
    MODIFY `updated_at` DATETIME(3) NULL,
    MODIFY `link_payment` VARCHAR(191) NULL,
    MODIFY `doorid` BIGINT NULL,
    MODIFY `doorkey` VARCHAR(191) NULL;
